source "https://rubygems.org"

gem "fluentd", "1.14.2"
gem "oj", "3.11.3"
gem "fluent-plugin-gcloud-pubsub-custom", "~> 1.5.0"
gem "fluent-plugin-record-modifier", "~> 2.1.0"
gem "fluent-plugin-flowcounter-simple", "~> 0.1.0"
gem "fluent-plugin-gc", "~> 0.0.3"
