// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluentPVCOperator) DeepCopyInto(out *FluentPVCOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluentPVCOperator.
func (in *FluentPVCOperator) DeepCopy() *FluentPVCOperator {
	if in == nil {
		return nil
	}
	out := new(FluentPVCOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FluentPVCOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluentPVCOperatorList) DeepCopyInto(out *FluentPVCOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FluentPVCOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluentPVCOperatorList.
func (in *FluentPVCOperatorList) DeepCopy() *FluentPVCOperatorList {
	if in == nil {
		return nil
	}
	out := new(FluentPVCOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FluentPVCOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluentPVCOperatorSpec) DeepCopyInto(out *FluentPVCOperatorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluentPVCOperatorSpec.
func (in *FluentPVCOperatorSpec) DeepCopy() *FluentPVCOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(FluentPVCOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluentPVCOperatorStatus) DeepCopyInto(out *FluentPVCOperatorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluentPVCOperatorStatus.
func (in *FluentPVCOperatorStatus) DeepCopy() *FluentPVCOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(FluentPVCOperatorStatus)
	in.DeepCopyInto(out)
	return out
}
